### ISSUE TITLE
Information support

### ISSUE THREAD

**Issue by hildemann** [hclimente/spada#3]
Hi, 
I would like to use spada for a project of mine. Therefore I am seeking answers to questions I could not solve from reading the paper or supplement.
1. The spada paper states that spada: 
'discarded genes that either had an outlier expression in the tumor sample compared to normal tissues (...)or showed differential expression between the tumor and the normal samples(..).'

This means that a differential expression analysis is performed automatically by spada, correct? And how is this performed?

2. Regarding the input expression.tsv files: 
     ' transcript        1       2       3
       ENST12.3        0       1       2
       ENST08.1        0       1       2 ........'

Do these columns refer to TPM values of **isoforms**  1 to 3? Or what do the multiple TPM values per transcript stand for.

Thank you for your suggestions.

**Comment by hclimente** [comment]
Thanks for your interest in our work!

First, a word of caution. The current version of spada is a complete re-implementation of the software used in the paper, which relied too heavily on our particular setup, and was confusing for new users. So bear in mind that it's, to some degree, untested. I personally recommend using this version over the previous one, but with caution, double-checking the results (and letting us know of any discrepancy!). If you are still interested in running the original code, this is probably a good place to start: https://github.com/hclimente/spada/tree/ac407958c2617d433e45ca111f50273cf895d208

That said,

1. Yes, spada conducts a differential expression study. Think of it as an outlier detector: for each patient and gene, it checks that the difference in gene expression between the tumor and the matching healthy tissue is not higher than 95% of the differences in expression observed between all pairs ot healthy tissues for that gene.

2. The first row includes the sample names (that's what 1, 2, 3 represent). The remaining rows contain the TPMs of each particular transcript (one per column).

Best regards.
