### ISSUE TITLE
Switch detection procedure 

### ISSUE THREAD

**Issue by hildemann** [hclimente/spada#5]
Hi @hclimente , 
working with spada i do like the results. But since you said in a previous issue that the current version of spada is a '_complete re-implementation of the software used in the paper_', I wondered whether the switch detection conditions are still the same ones, as describes in the paper. 
For example in the paper it is stated that : 
'_We only kept those cases for which the tumor isoform PSI was higher than the normal isoform in the tumor sample and the normal isoform PSI in the normal sample was higher than the value for the tumor isoform_'
However in my analysis, spada reported the situation seen below as a switch, even though in both samples the normal isoform had a bigger psi (y axis = psi).

<img align="center" src="https://user-images.githubusercontent.com/65225674/107231483-a5e9e900-6a20-11eb-95a4-ef23bc904bde.JPG" width="500" height="500">

So are the switch detection criteria now (in the current spada version) still the same as described in the paper ?  Your advice would be greatly appreciated.
Thanks!

**Comment by hclimente** [comment]
Thanks for your feedback.

Indeed, I did not implement that check in spada. For reference, these are the criteria that a switch must meet:

1. "Big enough" delta PSI change in both normal and tumor isoforms.
2. Gene not-differentially expressed.
3. Gene expression higher than the specified threshold in both cases and controls.
